# Workflow-ի անունը, որը կերևա GitHub-ի Actions բաժնում
name: Python CI

# Ե՞րբ պետք է այս workflow-ն աշխատի
on:
  push:
    branches: [ "main" ] # "main" ճյուղ push անելիս
  pull_request:
    branches: [ "main" ] # "main" ճյուղի վրա pull request բացելիս

# Աշխատանքները (jobs), որոնք պետք է կատարվեն
jobs:
  build:
    # Վիրտուալ մեքենայի տեսակը, որի վրա պետք է աշխատի մեր job-ը
    runs-on: ubuntu-latest

    # Քայլերի հաջորդականությունը
    steps:
    # Քայլ 1: Ներբեռնում է ձեր ռեպոզիտորիայի կոդը վիրտուալ մեքենայի մեջ
    - name: Checkout repository
      uses: actions/checkout@v3

    # Քայլ 2: Տեղադրում է Python-ի նշված տարբերակը
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    # Քայլ 3: Տեղադրում է բոլոր անհրաժեշտ գրադարանները (flask, pytest)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Քայլ 4: Աշխատեցնում է մեր գրած թեստերը pytest-ի միջոցով
    - name: Run tests with pytest
      run: pytest
